kind = "mobile"
previewPath = "/farmerpro-mobile/"
title = "FarmerPro Mobile"
version = "1.0.0"
id = "artifacts/farmerpro-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/farmerpro-mobile/" ]
localPort = 20357

[services.development]
run = "pnpm --filter @workspace/farmerpro-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/farmerpro-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/farmerpro-mobile", "run", "serve" ]

[services.env]
PORT = "20357"
BASE_PATH = "/farmerpro-mobile/"
